# Ajuste para garantir o formato JDBC na URL do Railway
spring.datasource.url=jdbc:${MYSQL_PUBLIC_URL}
spring.datasource.username=${root}
spring.datasource.password=${1001}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Formatação padrão para data no Spring Boot
spring.mvc.format.date=yyyy-MM-dd